language: java

jdk:
  - oraclejdk8

script: "./gradlew clean build -x test"

services:
  - redis

# whitelist
branches:
  only:
    - 2.x
    - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
